language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE django_db;" -U postgres
  - psql -c "CREATE USER django_user WITH PASSWORD '0000';" -U postgres
  - cd backend

script:
  - python manage.py test --settings=config.settings.test
